// Questions
var q = [
	'What do you understand that others don&#39;t?',
	'Why will you succeed?',
	'How big an opportunity is there?',
	'What problems/hurdles are you anticipating?',
	'Who would use your product?',
	'How much does customer acquisition cost?',
	'How will you make money?',
	'How much money could you make per year?',
	'How many users do you have?',
	'What is your user growth rate?',
	'How many users are paying?',
	'How are you meeting customers?',
	'How are you understanding customer needs?',
	'How will you get users?',
	'Who would you hire or how would you add to your team?',
	
	'So what are you working on?',
	'Do you have a demo?',
	'Where is the rocket science here?',
	'How does your product work in more detail?',
	'How is your product different?',
	'What are you going to do next?',
	'What&#39;s new about what you make?',
	'What, exactly, makes you different from existing options?',
	'Who needs what you&#39;re making?',
	'How do you know customers need what you&#39;re making?',
	'Why isn&#39;t someone already doing this?',
	'What obstacles will you face and how will you overcome them?',
	'How will customers and/or users find out about you?',
	'What resistance will they have to trying you and how will you overcome it?',
	'What are the key things about your field that outsiders don&#39;t understand?',
	'What part of your project are you going to build first?',
	'Who is going to be your first paying customer?',
	'If your startup succeeds, what additional areas might you be able to expand into?',
	'Why did you choose this idea?',
	'What have you learned so far from working on your product?',
	'Six months from now, what&#39;s going to be your biggest problem?',
	'Where do new users come from?',
	'What is your growth like?',
	'What&#39;s the conversion rate?',
	'What makes new users try you?',
	'Why do the reluctant users hold back?',
	'What are the top things users want?',
	'What has surprised you about user behaviour?',
	'What&#39;s an impressive thing you have done?',
	'What do you understand about your users?',
	'Why did you pick this idea to work on?',
	'What domain expertise do you have?',
	'Who are your competitors?',
	'Who might become competitors?',
	'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	'What competition do you fear most?',
	'What is your distribution strategy?',
	'How did your team meet?',
	'Why did your team get together?',
	'Who in your team does what?',
	'Who is &quot;the boss&quot;?',
	'What will you do if we don&#39;t fund you?',
	'Would you relocate to Silicon Valley?',
	'How do we know your team will stick together?',
	'What else have you created together?',
	'Are you open to changing your idea? ',
	'What systems have you hacked?',
	'Tell us about a tough problem you solved?',
	'In what ways are you resourceful?',
	'Will you reincorporate as a US company?',
	'Will your team stick at this?',
	'Tell us something surprising you have done?',
	'What&#39;s the funniest thing that has happened to you?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s the biggest mistake you have made?',
	'What is your burn rate?',
	'How long can you go before funding?',
	'What is the next step with the product evolution?',
	'Have you raised funding?',
	'Who would be your next hire?',
	
	'How do you know people want this?',
	'What do you know about this space/product others don&#39;t know?',

	'Thousands of games come out every year, how do you plan to be the one to push through?',
	'You are only two people are you sure you can make the game?',
	'Games are very expensive to make, can you make the game with what we give from Innofounder?',
	'Is it a responsible business strategy to bet your company on grants?',
	'You say you have a huge discord server, could that be a bias for the survey?',
	'What barriers to entry do you foresee for disseminating your game into market?',
	'How do you plan to distribute your game?',
	'What do you expect the timeline to be?',
	'How have you validated that the pricing strategy aligns with market terms?',
	'What are you gonna do if you do not get Innofounder?',
	'How do you know we can do it?',
	'What is your staffing plan, how many people would you like to get on your team?',
	'How do you think that Innofounder will increase your chance of success beyond financial means?',
	'Beyond financial support, what is the most important aspect of Innofounder for you?',
	'How will Innofounder contribute to your project?',
	'How will you grow the business?',
	'Where are you in 12 months?',
	'How will you get more funding?',
	'Who is your customer?',
	'How do you know they will pay for your game?',
	'Not gameplay or design?',
	'How long will they play?',
	'How will you monetize?',
	'What is your long term expectations after the programme?',
	'The name, why, does it mean anything?',
	'What is a roguelike?',
	'What exactly is a knowledge-based?',
	'How will you contribute to the program?',
	'How did you get such a big community?',
	'What makes your team special?',
	'What makes your product special?',
	'How do you know that the market is underserved?',
	'What will you do if you do not land future funding?',
	'Why can people not stop thinking about your games specifically?',
	'What does Heli.os mean?',
	'Why does these genre create thriving communities?',
	'Are you really first movers?',
	'Expand on what you mean by connected with target audience',
	'How did you estimate 50 million DKK, that sounds like a lot',
	'What did you gain from Digital Tech Summit?',
	'How far in the process are you in the dialogue with the publisher?',
	'Do you already have a booth for testing at Copenhagen Gaming Week?',
	'What technical debt have you solved?',
	'How is your marketing strategy going?',
	'How will you evolve your marketing strategy?',
	'How can you be sure you\'ll reach Alpha in 12 months?',
	'How come you are not making a smaller game so you can release during Innofounder?',
	'Explain how you would choose crowdfunding or publishing',
	'How are you setting a precedence for aspiring game developers?',
	'How can you know that your niche in the market is underserved?',
	'How many people want your game?',
	'Why do people want your game?',
	'How can you know people want your game?',
	'What skills are you lacking to make the game?',
	'What would a first hire be?',
	'Why wont people stop thinking about Heli.os?',
	'Why are you only 2 founders?',
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];